name: front-test

on:
  push:
    branches: ["**"]

jobs:
  front-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: RÃ©cup du code
        uses: actions/checkout@v4
        with:
          node-version: 22

      - name: Installation node modules
        run: npm i  

      - name: Lance les test
        run: npm run test

      - name: Run Lighthouse CI
        run: npm run lhci autorun

      - name: Upload Lighthouse CI results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: ./.lighthouse